#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@turboacc[-1]
	add ucitrack turboacc
	set ucitrack.@turboacc[-1].init=turboacc
	commit ucitrack
EOF

[ -n "$(lsmod | grep mtkhnat)" ] && \
	uci set turboacc.config.sw_flow='0' && \
	uci set turboacc.config.hw_flow='0'

uci commit turboacc
chmod +x /etc/init.d/turboacc  
exit 0
